import pandas as pd
import matplotlib.pyplot as plt
import seaborn as se
import mysql.connector
import numpy as np

conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='582008',
    database='ecommerce'
)
cursor = conn.cursor()


# Intermediate Questions

# 1. Calculate the number of orders per month in 2018

query6 = """ Select monthname(orders.order_purchase_timestamp) , count(orders.order_id) as Total_orders from orders
where year(orders.order_purchase_timestamp) = 2018
group by monthname(orders.order_purchase_timestamp)"""

cursor.execute(query6)
data6 = cursor.fetchall
print(data6)


# 2. Find the average number of products per order, grouped by customer city

query7 = """Select customers.customer_city , avg(order_item_id) as average_orders from customers
join orders
on customers.customer_id = orders.customer_id
join order_items
on orders.order_id = order_items.order_id
group by customers.customer_city"""

cursor.execute(query7)
data7 = cursor.fetchall()
print(data7)

# 3. Calculate the percentage of total revenue contributed by each product category

query8 = """select products.product_category , round((sum(ecommerce.payments.payment_value)/(select sum(ecommerce.payments.payment_value) from ecommerce.payments))*100,2) as total_Payment from products
join order_items
on products.product_id =  order_items.product_id
join payments
on order_items.order_id = payments.order_id
group by products.product_category order by total_Payment desc"""
cursor.execute(query8)
data8 = cursor.fetchall()
print(data8)


# 4.Identify the correlation between product price and the number of times a product has been purchased

query9 = """select products.product_category , count(order_items.order_item_id) as Product_purchase , round(avg(order_items.price),2) as Price from products
join order_items
on products.product_id = order_items.product_id
group by products.product_category;"""
cursor.execute(query9)
data9 = cursor.fetchall()
print(data9)

df9 = pd.DataFrame(data9 , columns= ["Category" , "Product" , "Price"])
print(df9)
arr1 = df9["Product"]
arr2 = df9["Price"]
print(np.corrcoef([arr1,arr2]))


# 5.Calculate the total revenue generated by each seller, and rank them by revenue

query10 = """select order_items.seller_id , sum(payments.payment_value) as total_revenue from order_items
join payments
on order_items.order_id = payments.order_id
group by order_items.seller_id order by total_revenue desc"""

cursor.execute(query10)
data10 = cursor.fetchall()
df10 = pd.DataFrame(data10 , columns= ["seller ID" , "Revenue"])
print(df10.head(10))
